#!/bin/bash
# TODO expose these also as environment variables like `BRANCH=master pkgpr ...`?
VERSION="0.0.12"
SYNC="rsync -ra"
MESSAGE=""
BRANCH="master"
FILES=""
ORG="gentoo"
REPO="gentoo"
ACC=""
URL="github.com"
DESC="PR created by [pkgpr](https://github.com/APN-Pucky/pkgpr)."
FILES=()
CLOSES=""
BUG=""
NO_CLEANUP=""
TEST=""
TEST_FLAGS='--test-feature-scope always --append-emerge "--autounmask=y --autounmask-write --autounmask-continue --autounmask-use=y"'
DEBUG=""
YES=""
# was used to toggle tmp directory usage, but only tmp is supported for testing
TMP=""
DRAFT=""


GITLAB_OPT=""
GITHUB_OPT=""

# from https://stackoverflow.com/a/14203146
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      echo "Usage: pkgpr-$VERSION [options] [files]"
      echo "Options:"
      echo "  -h, --help: Show this help"
      echo "  -a, --account: Account to send PR to"
      echo "  -u, --url: URL of the git server (default: github.com)"
      echo "  -r, --repo: Repository to send PR to (default: gentoo)"
      echo "  -ar, --account-repo: Repository to send PR to"
      echo "  -c, --closes: Issue to close"
      echo "  -b, --bug: Bug to reference"
      echo "  -cp, --copy: Copy from that directory instead of cloning"
      echo "  --sync: rsync -ra (w/o deletes) or rsync -ra --delete (w/ deletes) to sync changes (default: rsync -ra)"
      echo "  -o, --org: Organization to send PR to (default: gentoo)"
      echo "  -d, --desc: Description of the PR"
      echo "  --draft: PR should be a draft"
      echo "  -f, --files: Files to add to the PR"
      echo "  -m, --message: commit message"
      echo "  -br, --branch: Branch to send PR to (default: master)"
      echo "  -nc, --no-cleanup: Do not cleanup the tmp repo after PR"
      echo "  -v, --version: Show version"
      echo "  -y, --yes: Skip confirmation. Won't show diff and will send PR immediately, unless pkgdev commit message is needed"
      echo "  -t, --test: Test the PR with pkg-testing-tool. Implies --tmp (default: false)"
      echo "  -tf, --test-flags: Flags to pass to pkg-testing-tool (default: $TEST_FLAGS)"
      echo "  --tmp: Use a tmp directory for the repo. Useful for parallel PRs and testing"
      echo ""
      echo "Example: pkgpr -a APN-Pucky -r sci app-misc/foo"
      exit 0
      ;;
    --draft)
      DRAFT="1"
      shift
      ;;
    --tmp)
      TMP="1"
      shift
      ;;
    -y|--yes)
      YES="1"
      shift
      ;;
    -v|--version)
      echo "pkgpr-$VERSION"
      exit 0
      ;;
    -t|--test)
      TEST="1"
      TMP="1"
      shift
      ;;
    -d|--debug)
      DEBUG="1"
      shift
      ;;
    -tf|--test-flags)
      TEST_FLAGS=$2
      shift
      shift
      ;;
    --sync)
      SYNC=$2
      shift
      shift
      ;;
    -c|--closes)
      CLOSES="-c $2"
      shift # past argument
      shift # past value
      ;;
    -b|--bug)
      BUG="-b $2"
      shift # past argument
      shift # past value
      ;;
    -a|--account)
      ACC="$2"
      shift # past argument
      shift # past value
      ;;
    -u|--url)
      URL="$2"
      shift # past argument
      shift # past value
      ;;
    -r|--repo)
      REPO="$2"
      shift # past argument
      shift # past value
      ;;
    -ar|--account-repo)
      AREPO="$3"
      shift # past argument
      shift # past value
      ;;
    -cp|--copy)
      COPY="$2"
      shift # past argument
      shift # past value
      ;;
    -o|--org)
        ORG="$2"
        shift # past argument
        shift # past value
        ;;
    -d|--desc)
        DESC="$2"
        shift # past argument
        shift # past value
        ;;
    # message
    -m|--message)
      MESSAGE="$2"
      shift # past argument
      shift # past value
      ;;
    # branch
    -br|--branch)
      BRANCH="$2"
      shift # past argument
      shift # past value
      ;;
    -nc|--no-cleanup)
      NO_CLEANUP="1"
      shift
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      FILES+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

if [ -z "${AREPO}" ]; then
    AREPO=${REPO}
fi

if [ -z "${ACC}" ]; then
    echo "No account specified"
    exit 1
fi

PRPREFIX=""

if [ -f ../metadata/layout.conf ]; then
    PRPREFIX="$(basename $(pwd))/"
    cd ..
fi

if [ -f ../../metadata/layout.conf ]; then
    PRPREFIX="$(basename $(dirname $(pwd)))/$(basename $(pwd))/"
    cd ../..
fi

if [ -f ../../metadata/layout.conf ]; then
    PRPREFIX="$(basename $(dirname $(dirname $(pwd))))/$(basename $(dirname $(pwd)))/$(basename $(pwd))/"
    cd ../../..
fi

# if no folder folder metadata/layout.conf exists abort, since must run on a gentoo repo
if [ ! -f metadata/layout.conf ]; then
    echo "No metadata/layout.conf found, not a gentoo repo."
    echo "It is recommended to run this script inside of a gentoo repository."
    exit 1
fi

OPWD=${PWD}
echo "Adding files: ${FILES[@]} from ${OPWD}"

cache_dir="${HOME}/.cache/pkgpr"
mkdir -p ${cache_dir}/${URL}/${ORG}
if [ ! -d ${cache_dir}/${URL}/${ORG}/${REPO} ]; then
  # clone the repo to cache if it does not exist
  git -C ${cache_dir}/${URL}/${ORG} clone --depth 1 git@${URL}:${ORG}/${REPO}.git -b ${BRANCH}
else
  # update the repo in cache
  git -C ${cache_dir}/${URL}/${ORG}/${REPO} fetch origin ${BRANCH}
fi

if [ -n "${TMP}" ]; then
  TEMP_DIR=$(mktemp -d)
  pushd ${TEMP_DIR}
#  copy the repo to the temp dir
  cp -r ${cache_dir}/${URL}/${ORG}/${REPO} ./${REPO}
  cd ${REPO}
else
  pushd ${cache_dir}/${URL}/${ORG}/${REPO}
fi

# checkout the base branch
git checkout -f origin/${BRANCH}
# create a new branch
NB=pkgpr_${BRANCH}_$(date +%s)
git checkout -b ${NB}

TEST_FILES=""

for file in ${FILES[@]}; do
    # we remove the trailing slash from folders for proper rsync copy of the whole folder
    dfile=${PRPREFIX}${file%/}
    # rsync to merge
    [ -n DEBUG ] && echo "$SYNC ${OPWD}/${dfile} $(dirname ${dfile})/"
    $SYNC ${OPWD}/${dfile} $(dirname ${dfile})/
    # remove every .build file in the dir
    find ${dfile} -name ".build" -exec rm -rf {} \;
    # find .ebuilds to append to TEST_FILES
    EBUILD_FILES=$(find ${dfile} -name "*.ebuild" -exec echo -n " -f {}" \;)
    TEST_FILES="${TEST_FILES} ${EBUILD_FILES}"
    # add to git
    git add ${dfile}
done

# 1. Review diff first
if [[ -z "${YES}" ]]
then
  git diff origin/${BRANCH}
fi

# 2. then quickly show trivial typos
# if no message 
if [ -z "${MESSAGE}" ]; then
    ARGS="${BUG} ${CLOSES}"
    pkgdev commit ${ARGS}
else
    ARGS="${BUG} ${CLOSES} -m ${MESSAGE}"
    pkgdev commit ${ARGS}
fi

# 3. test it
if [ -n "${TEST}" ]; then
    echo "sudo needed for testing: $ pkg-testing-tool ${TEST_FILES} ${TEST_FLAGS}"
    REPONAME=$(cat ./profiles/repo_name)
    echo "pkgpr-${REPONAME}" > ./profiles/repo_name
    # portage needs that for executing in this folder (i.e. gen manifest), pkgdev commit needs original
    sudo sh -c "chown portage:portage -R .. ; pkg-testing-tool ${TEST_FILES} ${TEST_FLAGS} ; chown $USER:$USER -R .." || exit 1 # exit on error or failure or interupt
    echo "${REPONAME}" > ./profiles/repo_name
fi

git remote add pkgpr_${ACC} git@${URL}:${ACC}/${AREPO}.git

if [[ -n "${DRAFT}" ]] 
then
  GITHUB_OPT="${GITHUB_OPT} --draft"
  GITLAB_OPT="${GITLAB_OPT} -o merge_request.draft"
fi

if [[ -z "${YES}" ]]
then
  read -p "Send PR? [y]" -n 1 -r
fi
if [[ $REPLY =~ ^[Yy]*$ ]]
then
  git push -u pkgpr_${ACC} ${NB} -o merge_request.create -o merge_request.target_project=${ORG}/${REPO} -o merge_request.target=${BRANCH} -o merge_request.remove_source_branch -o merge_request.description="${DESC}" ${GITLAB_OPT}
  # github does not use the options like gitlab
  # check if github in URL
  if [[ ${URL} == "github.com" ]]; then
    echo "Github detected, opening PR"
    gh pr create -R ${ORG}/${REPO} --fill --base ${BRANCH} --head ${ACC}:${NB} --body "${DESC}" ${GITHUB_OPT}
  fi
fi

popd

# Only cleanup if in tmp mode
if [[ -n "${TMP}" && -n "${TEMP_DIR}" && -z "${NO_CLEANUP}" ]]; then
    rm -rf ${TEMP_DIR}
fi
